spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: KakhianiIlyaKakhaberievichBKS2202
  accessExpiration: 3600000 # 1 час для Access токена
  refreshExpiration: 604800000 # 7 дней для Refresh токена

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverIK.jks
    key-store-type: JKS
    key-store-password: serverIKPass
    key-alias: serverIK
keys:
  private: ${PRIVATE_KEY_PATH}
